# Generated by Django 4.2.6 on 2023-11-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsr', models.IntegerField()),
                ('asset_nm', models.CharField(max_length=255)),
                ('ct_cl', models.CharField(max_length=255)),
                ('genre_of_ct_cl', models.CharField(max_length=255)),
                ('use_tms', models.IntegerField()),
                ('strt_dt', models.DateTimeField()),
                ('vod분류', models.CharField(max_length=255)),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
            ],
        ),
    ]
