# Generated by Django 4.2.6 on 2023-11-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_video'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='service_video',
        ),
    ]
